/*
 * Nuvio PS5
 * Copyright (C) 2026 Husam Osman
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/* Fonts, icons and artwork from assets/ (paths relative to nuvio-app/),
 * compiled into the eboot, so nothing depends on the app's file layout.
 * Generated by scripts/gen_assets.py. */
#include "ui_assets.h"

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_regular\nnuvio_blob_font_inter_regular:\n.incbin \"assets/fonts/Inter-Regular.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_regular_end\nnuvio_blob_font_inter_regular_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_regular[], nuvio_blob_font_inter_regular_end[];
ui_asset ui_asset_font_inter_regular(void)
{
    ui_asset a = {nuvio_blob_font_inter_regular, (size_t)(nuvio_blob_font_inter_regular_end - nuvio_blob_font_inter_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_medium\nnuvio_blob_font_inter_medium:\n.incbin \"assets/fonts/Inter-Medium.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_medium_end\nnuvio_blob_font_inter_medium_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_medium[], nuvio_blob_font_inter_medium_end[];
ui_asset ui_asset_font_inter_medium(void)
{
    ui_asset a = {nuvio_blob_font_inter_medium, (size_t)(nuvio_blob_font_inter_medium_end - nuvio_blob_font_inter_medium) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_semibold\nnuvio_blob_font_inter_semibold:\n.incbin \"assets/fonts/Inter-SemiBold.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_semibold_end\nnuvio_blob_font_inter_semibold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_semibold[], nuvio_blob_font_inter_semibold_end[];
ui_asset ui_asset_font_inter_semibold(void)
{
    ui_asset a = {nuvio_blob_font_inter_semibold, (size_t)(nuvio_blob_font_inter_semibold_end - nuvio_blob_font_inter_semibold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_inter_bold\nnuvio_blob_font_inter_bold:\n.incbin \"assets/fonts/Inter-Bold.ttf\"\n.byte 0\n.global nuvio_blob_font_inter_bold_end\nnuvio_blob_font_inter_bold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_inter_bold[], nuvio_blob_font_inter_bold_end[];
ui_asset ui_asset_font_inter_bold(void)
{
    ui_asset a = {nuvio_blob_font_inter_bold, (size_t)(nuvio_blob_font_inter_bold_end - nuvio_blob_font_inter_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_roboto_regular\nnuvio_blob_font_roboto_regular:\n.incbin \"assets/fonts/Roboto-Regular.ttf\"\n.byte 0\n.global nuvio_blob_font_roboto_regular_end\nnuvio_blob_font_roboto_regular_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_roboto_regular[], nuvio_blob_font_roboto_regular_end[];
ui_asset ui_asset_font_roboto_regular(void)
{
    ui_asset a = {nuvio_blob_font_roboto_regular, (size_t)(nuvio_blob_font_roboto_regular_end - nuvio_blob_font_roboto_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_roboto_bold\nnuvio_blob_font_roboto_bold:\n.incbin \"assets/fonts/Roboto-Bold.ttf\"\n.byte 0\n.global nuvio_blob_font_roboto_bold_end\nnuvio_blob_font_roboto_bold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_roboto_bold[], nuvio_blob_font_roboto_bold_end[];
ui_asset ui_asset_font_roboto_bold(void)
{
    ui_asset a = {nuvio_blob_font_roboto_bold, (size_t)(nuvio_blob_font_roboto_bold_end - nuvio_blob_font_roboto_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_naskh_regular\nnuvio_blob_font_naskh_regular:\n.incbin \"assets/fonts/NotoNaskhArabicUI-Regular.ttf\"\n.byte 0\n.global nuvio_blob_font_naskh_regular_end\nnuvio_blob_font_naskh_regular_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_naskh_regular[], nuvio_blob_font_naskh_regular_end[];
ui_asset ui_asset_font_naskh_regular(void)
{
    ui_asset a = {nuvio_blob_font_naskh_regular, (size_t)(nuvio_blob_font_naskh_regular_end - nuvio_blob_font_naskh_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_naskh_bold\nnuvio_blob_font_naskh_bold:\n.incbin \"assets/fonts/NotoNaskhArabicUI-Bold.ttf\"\n.byte 0\n.global nuvio_blob_font_naskh_bold_end\nnuvio_blob_font_naskh_bold_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_naskh_bold[], nuvio_blob_font_naskh_bold_end[];
ui_asset ui_asset_font_naskh_bold(void)
{
    ui_asset a = {nuvio_blob_font_naskh_bold, (size_t)(nuvio_blob_font_naskh_bold_end - nuvio_blob_font_naskh_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_font_noto_emoji\nnuvio_blob_font_noto_emoji:\n.incbin \"assets/fonts/NotoEmoji.ttf\"\n.byte 0\n.global nuvio_blob_font_noto_emoji_end\nnuvio_blob_font_noto_emoji_end:\n.previous\n");
extern const uint8_t nuvio_blob_font_noto_emoji[], nuvio_blob_font_noto_emoji_end[];
ui_asset ui_asset_font_noto_emoji(void)
{
    ui_asset a = {nuvio_blob_font_noto_emoji, (size_t)(nuvio_blob_font_noto_emoji_end - nuvio_blob_font_noto_emoji) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_img_wordmark\nnuvio_blob_img_wordmark:\n.incbin \"assets/app_logo_wordmark.png\"\n.byte 0\n.global nuvio_blob_img_wordmark_end\nnuvio_blob_img_wordmark_end:\n.previous\n");
extern const uint8_t nuvio_blob_img_wordmark[], nuvio_blob_img_wordmark_end[];
ui_asset ui_asset_img_wordmark(void)
{
    ui_asset a = {nuvio_blob_img_wordmark, (size_t)(nuvio_blob_img_wordmark_end - nuvio_blob_img_wordmark) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_aspect_ratio\nnuvio_blob_svg_aspect_ratio:\n.incbin \"assets/icons/ic_player_aspect_ratio.svg\"\n.byte 0\n.global nuvio_blob_svg_aspect_ratio_end\nnuvio_blob_svg_aspect_ratio_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_aspect_ratio[], nuvio_blob_svg_aspect_ratio_end[];
ui_asset ui_asset_svg_aspect_ratio(void)
{
    ui_asset a = {nuvio_blob_svg_aspect_ratio, (size_t)(nuvio_blob_svg_aspect_ratio_end - nuvio_blob_svg_aspect_ratio) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_audio_filled\nnuvio_blob_svg_audio_filled:\n.incbin \"assets/icons/ic_player_audio_filled.svg\"\n.byte 0\n.global nuvio_blob_svg_audio_filled_end\nnuvio_blob_svg_audio_filled_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_audio_filled[], nuvio_blob_svg_audio_filled_end[];
ui_asset ui_asset_svg_audio_filled(void)
{
    ui_asset a = {nuvio_blob_svg_audio_filled, (size_t)(nuvio_blob_svg_audio_filled_end - nuvio_blob_svg_audio_filled) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_audio_outline\nnuvio_blob_svg_audio_outline:\n.incbin \"assets/icons/ic_player_audio_outline.svg\"\n.byte 0\n.global nuvio_blob_svg_audio_outline_end\nnuvio_blob_svg_audio_outline_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_audio_outline[], nuvio_blob_svg_audio_outline_end[];
ui_asset ui_asset_svg_audio_outline(void)
{
    ui_asset a = {nuvio_blob_svg_audio_outline, (size_t)(nuvio_blob_svg_audio_outline_end - nuvio_blob_svg_audio_outline) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_episodes\nnuvio_blob_svg_episodes:\n.incbin \"assets/icons/ic_player_episodes.svg\"\n.byte 0\n.global nuvio_blob_svg_episodes_end\nnuvio_blob_svg_episodes_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_episodes[], nuvio_blob_svg_episodes_end[];
ui_asset ui_asset_svg_episodes(void)
{
    ui_asset a = {nuvio_blob_svg_episodes, (size_t)(nuvio_blob_svg_episodes_end - nuvio_blob_svg_episodes) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_pause\nnuvio_blob_svg_pause:\n.incbin \"assets/icons/ic_player_pause.svg\"\n.byte 0\n.global nuvio_blob_svg_pause_end\nnuvio_blob_svg_pause_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_pause[], nuvio_blob_svg_pause_end[];
ui_asset ui_asset_svg_pause(void)
{
    ui_asset a = {nuvio_blob_svg_pause, (size_t)(nuvio_blob_svg_pause_end - nuvio_blob_svg_pause) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_play\nnuvio_blob_svg_play:\n.incbin \"assets/icons/ic_player_play.svg\"\n.byte 0\n.global nuvio_blob_svg_play_end\nnuvio_blob_svg_play_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_play[], nuvio_blob_svg_play_end[];
ui_asset ui_asset_svg_play(void)
{
    ui_asset a = {nuvio_blob_svg_play, (size_t)(nuvio_blob_svg_play_end - nuvio_blob_svg_play) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_skip_next\nnuvio_blob_svg_skip_next:\n.incbin \"assets/icons/ic_player_skip_next.svg\"\n.byte 0\n.global nuvio_blob_svg_skip_next_end\nnuvio_blob_svg_skip_next_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_skip_next[], nuvio_blob_svg_skip_next_end[];
ui_asset ui_asset_svg_skip_next(void)
{
    ui_asset a = {nuvio_blob_svg_skip_next, (size_t)(nuvio_blob_svg_skip_next_end - nuvio_blob_svg_skip_next) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_source\nnuvio_blob_svg_source:\n.incbin \"assets/icons/ic_player_source.svg\"\n.byte 0\n.global nuvio_blob_svg_source_end\nnuvio_blob_svg_source_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_source[], nuvio_blob_svg_source_end[];
ui_asset ui_asset_svg_source(void)
{
    ui_asset a = {nuvio_blob_svg_source, (size_t)(nuvio_blob_svg_source_end - nuvio_blob_svg_source) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_subtitles\nnuvio_blob_svg_subtitles:\n.incbin \"assets/icons/ic_player_subtitles.svg\"\n.byte 0\n.global nuvio_blob_svg_subtitles_end\nnuvio_blob_svg_subtitles_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_subtitles[], nuvio_blob_svg_subtitles_end[];
ui_asset ui_asset_svg_subtitles(void)
{
    ui_asset a = {nuvio_blob_svg_subtitles, (size_t)(nuvio_blob_svg_subtitles_end - nuvio_blob_svg_subtitles) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_check\nnuvio_blob_svg_check:\n.incbin \"assets/icons/ic_ui_check.svg\"\n.byte 0\n.global nuvio_blob_svg_check_end\nnuvio_blob_svg_check_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_check[], nuvio_blob_svg_check_end[];
ui_asset ui_asset_svg_check(void)
{
    ui_asset a = {nuvio_blob_svg_check, (size_t)(nuvio_blob_svg_check_end - nuvio_blob_svg_check) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_chevron_left\nnuvio_blob_svg_chevron_left:\n.incbin \"assets/icons/ic_ui_chevron_left.svg\"\n.byte 0\n.global nuvio_blob_svg_chevron_left_end\nnuvio_blob_svg_chevron_left_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_chevron_left[], nuvio_blob_svg_chevron_left_end[];
ui_asset ui_asset_svg_chevron_left(void)
{
    ui_asset a = {nuvio_blob_svg_chevron_left, (size_t)(nuvio_blob_svg_chevron_left_end - nuvio_blob_svg_chevron_left) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_chevron_right\nnuvio_blob_svg_chevron_right:\n.incbin \"assets/icons/ic_ui_chevron_right.svg\"\n.byte 0\n.global nuvio_blob_svg_chevron_right_end\nnuvio_blob_svg_chevron_right_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_chevron_right[], nuvio_blob_svg_chevron_right_end[];
ui_asset ui_asset_svg_chevron_right(void)
{
    ui_asset a = {nuvio_blob_svg_chevron_right, (size_t)(nuvio_blob_svg_chevron_right_end - nuvio_blob_svg_chevron_right) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_fast_forward\nnuvio_blob_svg_fast_forward:\n.incbin \"assets/icons/ic_ui_fast_forward.svg\"\n.byte 0\n.global nuvio_blob_svg_fast_forward_end\nnuvio_blob_svg_fast_forward_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_fast_forward[], nuvio_blob_svg_fast_forward_end[];
ui_asset ui_asset_svg_fast_forward(void)
{
    ui_asset a = {nuvio_blob_svg_fast_forward, (size_t)(nuvio_blob_svg_fast_forward_end - nuvio_blob_svg_fast_forward) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_fast_rewind\nnuvio_blob_svg_fast_rewind:\n.incbin \"assets/icons/ic_ui_fast_rewind.svg\"\n.byte 0\n.global nuvio_blob_svg_fast_rewind_end\nnuvio_blob_svg_fast_rewind_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_fast_rewind[], nuvio_blob_svg_fast_rewind_end[];
ui_asset ui_asset_svg_fast_rewind(void)
{
    ui_asset a = {nuvio_blob_svg_fast_rewind, (size_t)(nuvio_blob_svg_fast_rewind_end - nuvio_blob_svg_fast_rewind) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global nuvio_blob_svg_warning\nnuvio_blob_svg_warning:\n.incbin \"assets/icons/ic_ui_warning.svg\"\n.byte 0\n.global nuvio_blob_svg_warning_end\nnuvio_blob_svg_warning_end:\n.previous\n");
extern const uint8_t nuvio_blob_svg_warning[], nuvio_blob_svg_warning_end[];
ui_asset ui_asset_svg_warning(void)
{
    ui_asset a = {nuvio_blob_svg_warning, (size_t)(nuvio_blob_svg_warning_end - nuvio_blob_svg_warning) - 1};
    return a;
}
