#pragma once
/* Files compiled into the app (ui_assets.c, .incbin). Generated by
 * scripts/gen_assets.py - edit that, not this. */
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ui_asset {
    const uint8_t *data;
    size_t size;          /* data[size] is a 0 byte (SVG text) */
} ui_asset;

ui_asset ui_asset_font_inter_regular(void);
ui_asset ui_asset_font_inter_medium(void);
ui_asset ui_asset_font_inter_semibold(void);
ui_asset ui_asset_font_inter_bold(void);
ui_asset ui_asset_font_roboto_regular(void);
ui_asset ui_asset_font_roboto_bold(void);
ui_asset ui_asset_font_naskh_regular(void);
ui_asset ui_asset_font_naskh_bold(void);
ui_asset ui_asset_font_noto_emoji(void);
ui_asset ui_asset_img_wordmark(void);
ui_asset ui_asset_svg_aspect_ratio(void);
ui_asset ui_asset_svg_audio_filled(void);
ui_asset ui_asset_svg_audio_outline(void);
ui_asset ui_asset_svg_episodes(void);
ui_asset ui_asset_svg_pause(void);
ui_asset ui_asset_svg_play(void);
ui_asset ui_asset_svg_skip_next(void);
ui_asset ui_asset_svg_source(void);
ui_asset ui_asset_svg_subtitles(void);
ui_asset ui_asset_svg_check(void);
ui_asset ui_asset_svg_chevron_left(void);
ui_asset ui_asset_svg_chevron_right(void);
ui_asset ui_asset_svg_fast_forward(void);
ui_asset ui_asset_svg_fast_rewind(void);
ui_asset ui_asset_svg_warning(void);

#ifdef __cplusplus
}
#endif
