#!/usr/bin/env python3
"""Regenerates src/ui_assets.{h,c}: every file listed below and every
assets/icons/*.svg, compiled into the eboot with .incbin (paths relative to
nuvio-app/, where make runs). Run after adding or renaming an asset."""
import glob
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
FIXED = [
    ("font_inter_regular", "assets/fonts/Inter-Regular.ttf"),
    ("font_inter_medium", "assets/fonts/Inter-Medium.ttf"),
    ("font_inter_semibold", "assets/fonts/Inter-SemiBold.ttf"),
    ("font_inter_bold", "assets/fonts/Inter-Bold.ttf"),
    ("font_roboto_regular", "assets/fonts/Roboto-Regular.ttf"),
    ("font_roboto_bold", "assets/fonts/Roboto-Bold.ttf"),
    ("font_naskh_regular", "assets/fonts/NotoNaskhArabicUI-Regular.ttf"),
    ("font_naskh_bold", "assets/fonts/NotoNaskhArabicUI-Bold.ttf"),
    ("font_noto_emoji", "assets/fonts/NotoEmoji.ttf"),
    ("img_wordmark", "assets/app_logo_wordmark.png"),
]


def main():
    os.chdir(ROOT)
    assets = list(FIXED)
    for path in sorted(glob.glob("assets/icons/*.svg")):
        stem = os.path.basename(path)[:-4]
        name = "svg_" + stem.replace("ic_player_", "").replace("ic_ui_", "")
        assets.append((name, path))
    h = ["#pragma once",
         "/* Files compiled into the app (ui_assets.c, .incbin). Generated by",
         " * scripts/gen_assets.py - edit that, not this. */",
         "#include <stddef.h>", "#include <stdint.h>", "",
         "#ifdef __cplusplus", 'extern "C" {', "#endif", "",
         "typedef struct ui_asset {", "    const uint8_t *data;",
         "    size_t size;          /* data[size] is a 0 byte (SVG text) */",
         "} ui_asset;", ""]
    c = ["/* Fonts, icons and artwork from assets/ (paths relative to nuvio-app/),",
         " * compiled into the eboot, so nothing depends on the app's file layout.",
         " * Generated by scripts/gen_assets.py. */",
         '#include "ui_assets.h"', ""]
    for name, path in assets:
        h.append("ui_asset ui_asset_%s(void);" % name)
        c.append('__asm__(".section .rodata\\n.balign 16\\n.global nuvio_blob_%s\\n'
                 'nuvio_blob_%s:\\n.incbin \\"%s\\"\\n.byte 0\\n.global nuvio_blob_%s_end\\n'
                 'nuvio_blob_%s_end:\\n.previous\\n");' % (name, name, path, name, name))
        c.append("extern const uint8_t nuvio_blob_%s[], nuvio_blob_%s_end[];" % (name, name))
        c.append("ui_asset ui_asset_%s(void)\n{\n    ui_asset a = {nuvio_blob_%s, "
                 "(size_t)(nuvio_blob_%s_end - nuvio_blob_%s) - 1};\n    return a;\n}\n"
                 % (name, name, name, name))
    h += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    open("src/ui_assets.h", "w").write("\n".join(h))
    open("src/ui_assets.c", "w").write("\n".join(c))
    # The Makefile rebuilds ui_assets.o when any of these change.
    open("build-assets.mk", "w").write(
        "ASSET_FILES := " + " ".join(p for _, p in assets) + "\n")
    print("%d assets" % len(assets))


if __name__ == "__main__":
    main()
